### PR TITLE
Fix log message on initial Juniper alarm

### LINKED ISSUE #213: Yellow/Red alarm initial value "None"
On initial creation of a yellow or red alarm case, the initial state of the alarm is "None", this is not an integer value and probably should be a 0 instead. 
I do not know where in the code this value is deriving from.

```
2024-04-09 21:43:40 XXX-gw2 yellow alarms went from None to 1
2024-04-09 21:58:38 XXX-gw2 yellow alarms went from 1 to 0
2024-04-09 22:04:34 XXX-gw2 yellow alarms went from 0 to 1
```

### PR DESCRIPTION
**Pull request by johannaengland**
Closes #213. 

We got the log message "yellow alarms went from None to 1", because on the first Juniper alarm we create an event, which does not have an alarm count yet.

### CODE REVIEW

**Comment by hmpf** [comment]
Fun bug!

**Review by hmpf — COMMENTED** [review]
Question: what happens if we go from N to 0 alarms?

* Is there another message?
* Is the event closed?
* What order do the two happen in, if they both happen?

Intuitively, I would assume going from N to 0 alarms for a type&device closes the alarm for that type&device.

**Comment by johannaengland** [comment]
> Question: what happens if we go from N to 0 alarms?
> 
>     * Is there another message?

Yes, a log is added to the event that says exactly that.

>     * Is the event closed?

No, as in Zino1, events are never closed automatically, that has to happen manually.

**Comment by hmpf** [comment]
> > ```
> > * Is the event closed?
> > ```
> 
> No, as in Zino1, events are never closed automatically, that has to happen manually.

So if it goes back from 0 to N the event is reused?

Now it makes me wonder how clients show this. 0 is a good thing and should be shown different from bigger than 0. I guess we can test when we have a way to fake an event =)

**Review by hmpf — APPROVED** [review]

**Comment by johannaengland** [comment]
> So if it goes back from 0 to N the event is reused?

Yes, but only if the event has not been closed by then. 

> Now it makes me wonder how clients show this. 0 is a good thing and should be shown different from bigger than 0. I guess we can test when we have a way to fake an event =)

I would assume that clients show it just like any other event. But feel free to post that as an issue in Howitz

**Pull request merged**
